# Generated by Django 5.2.4 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models
import django.contrib.contenttypes.models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_vodlogo_alter_movie_logo_alter_series_logo'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='STRMFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('strm_path', models.CharField(help_text='Full path to the generated STRM file', max_length=1024)),
                ('nfo_path', models.CharField(blank=True, help_text='Full path to the generated NFO file', max_length=1024, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the STRM file was first generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the STRM file was last updated')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'STRM File',
                'verbose_name_plural': 'STRM Files',
            },
        ),
        migrations.AddIndex(
            model_name='strmfile',
            index=models.Index(fields=['content_type', 'content_id'], name='vod_strmfile_content_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strmfile',
            unique_together={('content_type', 'content_id')},
        ),
    ]






